const mongoose = require('mongoose');
const { connectDB, isConnected } = require('../config/db');
const Product = require('../models/Product');

const defaultProducts = [
  {
    "id": 1,
    "name": "Classic Cotton Crewneck T-Shirt",
    "brand": "Roadster",
    "category": "fashion",
    "subcategory": "T-Shirts",
    "description": "100% combed ring-spun breathable cotton casual crewneck t-shirt with reinforced double-stitched seams.",
    "price": 599,
    "originalPrice": 999,
    "discount": 40,
    "rating": 4.5,
    "reviews": 320,
    "reviewCount": 320,
    "stock": 40,
    "image": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80",
    "tags": [
      "tshirt",
      "cotton",
      "casual",
      "topwear",
      "fashion",
      "crewneck"
    ],
    "variants": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "id": 2,
    "name": "Slim-Fit Stretch Denim Jeans",
    "brand": "Levi's",
    "category": "fashion",
    "subcategory": "Jeans",
    "description": "Classic medium-wash 5-pocket denim jeans tailored in flexible stretch fabric for maximum movement.",
    "price": 1899,
    "originalPrice": 2999,
    "discount": 37,
    "rating": 4.6,
    "reviews": 284,
    "reviewCount": 284,
    "stock": 25,
    "image": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80",
    "tags": [
      "jeans",
      "denim",
      "pants",
      "bottomwear",
      "fashion",
      "slim-fit"
    ],
    "variants": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "id": 3,
    "name": "Casual Lightweight Bomber Jacket",
    "brand": "Zara",
    "category": "fashion",
    "subcategory": "Jackets",
    "description": "Water-resistant windbreaker bomber jacket featuring ribbed collar, secure zip pockets, and satin lining.",
    "price": 2499,
    "originalPrice": 3999,
    "discount": 38,
    "rating": 4.7,
    "reviews": 195,
    "reviewCount": 195,
    "stock": 18,
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80",
    "tags": [
      "jacket",
      "bomber",
      "outerwear",
      "winterwear",
      "fashion",
      "casual"
    ],
    "variants": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "id": 4,
    "name": "Breathable Pro Running Shoes",
    "brand": "Nike",
    "category": "fashion",
    "subcategory": "Footwear",
    "description": "Lightweight engineered mesh running shoes with responsive foam cushioning and high-traction rubber outsole.",
    "price": 3499,
    "originalPrice": 4999,
    "discount": 30,
    "rating": 4.8,
    "reviews": 450,
    "reviewCount": 450,
    "stock": 20,
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    "tags": [
      "shoes",
      "sneakers",
      "running",
      "footwear",
      "fashion",
      "sports"
    ],
    "variants": [
      "6",
      "7",
      "8",
      "9",
      "10",
      "11"
    ]
  },
  {
    "id": 5,
    "name": "Classic Leather White Sneakers",
    "brand": "Adidas",
    "category": "fashion",
    "subcategory": "Footwear",
    "description": "Timeless low-top white sneakers handcrafted in premium synthetic leather with padded collar.",
    "price": 2799,
    "originalPrice": 3999,
    "discount": 30,
    "rating": 4.7,
    "reviews": 312,
    "reviewCount": 312,
    "stock": 22,
    "image": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80",
    "tags": [
      "sneakers",
      "shoes",
      "white shoes",
      "footwear",
      "fashion",
      "casual"
    ],
    "variants": [
      "6",
      "7",
      "8",
      "9",
      "10",
      "11"
    ]
  },
  {
    "id": 6,
    "name": "Polarized Wayfarer Sunglasses",
    "brand": "Ray-Ban",
    "category": "fashion",
    "subcategory": "Accessories",
    "description": "UV400 protective polarized lenses in a lightweight tortoiseshell frame offering crystal-clear glare reduction.",
    "price": 1299,
    "originalPrice": 2199,
    "discount": 41,
    "rating": 4.4,
    "reviews": 168,
    "reviewCount": 168,
    "stock": 30,
    "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80",
    "tags": [
      "sunglasses",
      "eyewear",
      "accessories",
      "fashion",
      "polarized",
      "summer"
    ],
    "variants": null
  },
  {
    "id": 7,
    "name": "Minimalist Leather Wristwatch",
    "brand": "Fossil",
    "category": "fashion",
    "subcategory": "Watches",
    "description": "Japanese quartz movement watch with genuine brown leather strap and scratch-resistant mineral glass.",
    "price": 3199,
    "originalPrice": 4999,
    "discount": 36,
    "rating": 4.6,
    "reviews": 220,
    "reviewCount": 220,
    "stock": 14,
    "image": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&q=80",
    "tags": [
      "watch",
      "leather watch",
      "analog",
      "accessories",
      "fashion"
    ],
    "variants": null
  },
  {
    "id": 8,
    "name": "Casual Oxford Cotton Shirt",
    "brand": "Tommy Hilfiger",
    "category": "fashion",
    "subcategory": "Shirts",
    "description": "Button-down long sleeve casual Oxford cotton shirt with curved hemline and chest patch pocket.",
    "price": 1499,
    "originalPrice": 2499,
    "discount": 40,
    "rating": 4.5,
    "reviews": 185,
    "reviewCount": 185,
    "stock": 28,
    "image": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80",
    "tags": [
      "shirt",
      "oxford",
      "formal",
      "casual",
      "topwear",
      "fashion"
    ],
    "variants": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "id": 9,
    "name": "Fleece Pullover Hoodie",
    "brand": "Puma",
    "category": "fashion",
    "subcategory": "Hoodies",
    "description": "Cozy brushed fleece hoodie with adjustable drawstring hood, kangaroo front pocket, and ribbed cuffs.",
    "price": 1699,
    "originalPrice": 2799,
    "discount": 39,
    "rating": 4.7,
    "reviews": 270,
    "reviewCount": 270,
    "stock": 24,
    "image": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&q=80",
    "tags": [
      "hoodie",
      "pullover",
      "winterwear",
      "topwear",
      "fashion",
      "fleece"
    ],
    "variants": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "id": 10,
    "name": "Genuine Leather Bifold Wallet",
    "brand": "Woodland",
    "category": "fashion",
    "subcategory": "Accessories",
    "description": "Handmade full-grain leather wallet with RFID blocking layer, 8 card slots, and dual currency compartments.",
    "price": 799,
    "originalPrice": 1499,
    "discount": 47,
    "rating": 4.4,
    "reviews": 198,
    "reviewCount": 198,
    "stock": 35,
    "image": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80",
    "tags": [
      "wallet",
      "leather",
      "accessories",
      "rfid",
      "fashion"
    ],
    "variants": null
  },
  {
    "id": 11,
    "name": "Wireless Over-Ear Noise-Cancelling Headphones",
    "brand": "Sony",
    "category": "electronics",
    "subcategory": "Audio",
    "description": "Active noise cancellation (ANC), custom 40mm drivers, 30-hour battery life, and plush memory-foam earcups.",
    "price": 4999,
    "originalPrice": 7999,
    "discount": 38,
    "rating": 4.8,
    "reviews": 520,
    "reviewCount": 520,
    "stock": 15,
    "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    "tags": [
      "headphones",
      "audio",
      "wireless",
      "bluetooth",
      "anc",
      "electronics"
    ],
    "variants": null
  },
  {
    "id": 12,
    "name": "Smartwatch GPS Fitness Tracker",
    "brand": "Apple",
    "category": "electronics",
    "subcategory": "Wearables",
    "description": "Always-on Retina OLED display, SpO2 blood oxygen sensor, heart rate tracking, and 50m water resistance.",
    "price": 8999,
    "originalPrice": 12999,
    "discount": 31,
    "rating": 4.8,
    "reviews": 410,
    "reviewCount": 410,
    "stock": 12,
    "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    "tags": [
      "smartwatch",
      "fitness",
      "wearables",
      "gps",
      "electronics"
    ],
    "variants": null
  },
  {
    "id": 13,
    "name": "4K Ultra HD Action Camera",
    "brand": "GoPro",
    "category": "electronics",
    "subcategory": "Cameras",
    "description": "Capture crystal-clear 4K video at 60fps with electronic image stabilization and waterproof casing up to 30 meters.",
    "price": 5999,
    "originalPrice": 9499,
    "discount": 37,
    "rating": 4.6,
    "reviews": 230,
    "reviewCount": 230,
    "stock": 10,
    "image": "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&q=80",
    "tags": [
      "camera",
      "action camera",
      "4k",
      "video",
      "electronics",
      "sports"
    ],
    "variants": null
  },
  {
    "id": 14,
    "name": "Shockproof Slim Phone Case",
    "brand": "Spigen",
    "category": "electronics",
    "subcategory": "Mobile Accessories",
    "description": "Military-grade drop protection with air-cushion corners, raised camera bezel, and matte anti-slip grip.",
    "price": 499,
    "originalPrice": 899,
    "discount": 44,
    "rating": 4.5,
    "reviews": 310,
    "reviewCount": 310,
    "stock": 50,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp",
    "tags": [
      "phone case",
      "mobile accessories",
      "cover",
      "shockproof",
      "electronics"
    ],
    "variants": null
  },
  {
    "id": 15,
    "name": "Ergonomic Wireless Optical Mouse",
    "brand": "Logitech",
    "category": "electronics",
    "subcategory": "Computer Accessories",
    "description": "Precision 2.4GHz wireless tracking, contoured rubber side grips, silent click buttons, and 18-month battery life.",
    "price": 799,
    "originalPrice": 1299,
    "discount": 38,
    "rating": 4.6,
    "reviews": 245,
    "reviewCount": 245,
    "stock": 26,
    "image": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80",
    "tags": [
      "mouse",
      "wireless mouse",
      "computer accessories",
      "peripherals",
      "electronics"
    ],
    "variants": null
  },
  {
    "id": 16,
    "name": "Fast Charging Braided USB-C Cable (2m)",
    "brand": "Anker",
    "category": "electronics",
    "subcategory": "Cables",
    "description": "Heavy-duty double-braided nylon jacket with 60W power delivery support and 10,000+ bend lifespan.",
    "price": 349,
    "originalPrice": 699,
    "discount": 50,
    "rating": 4.4,
    "reviews": 180,
    "reviewCount": 180,
    "stock": 60,
    "image": "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp",
    "tags": [
      "cable",
      "usb-c",
      "fast charging",
      "charger",
      "electronics"
    ],
    "variants": null
  },
  {
    "id": 17,
    "name": "RGB Mechanical Gaming Keyboard",
    "brand": "Razer",
    "category": "electronics",
    "subcategory": "Gaming Accessories",
    "description": "Tactile blue switches with 50-million keystroke durability, per-key RGB backlighting, and magnetic wrist rest.",
    "price": 3299,
    "originalPrice": 5499,
    "discount": 40,
    "rating": 4.7,
    "reviews": 340,
    "reviewCount": 340,
    "stock": 16,
    "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80",
    "tags": [
      "keyboard",
      "mechanical keyboard",
      "gaming",
      "rgb",
      "electronics"
    ],
    "variants": null
  },
  {
    "id": 18,
    "name": "True Wireless Earbuds with ANC",
    "brand": "JBL",
    "category": "electronics",
    "subcategory": "Audio",
    "description": "Dual microphone noise cancellation, IPX5 water resistance, touch controls, and compact wireless charging case.",
    "price": 2999,
    "originalPrice": 4999,
    "discount": 40,
    "rating": 4.6,
    "reviews": 290,
    "reviewCount": 290,
    "stock": 22,
    "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80",
    "tags": [
      "earbuds",
      "audio",
      "wireless",
      "bluetooth",
      "tws",
      "electronics"
    ],
    "variants": null
  },
  {
    "id": 19,
    "name": "10000mAh Ultra-Slim Power Bank",
    "brand": "Mi",
    "category": "electronics",
    "subcategory": "Mobile Accessories",
    "description": "Dual USB output with 22.5W two-way fast charging, aluminum alloy metal shell, and smart multi-protection chip.",
    "price": 1199,
    "originalPrice": 1999,
    "discount": 40,
    "rating": 4.5,
    "reviews": 375,
    "reviewCount": 375,
    "stock": 35,
    "image": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&q=80",
    "tags": [
      "power bank",
      "battery",
      "fast charge",
      "mobile accessories",
      "electronics"
    ],
    "variants": null
  },
  {
    "id": 20,
    "name": "Portable Bluetooth Speaker Waterproof",
    "brand": "Boat",
    "category": "electronics",
    "subcategory": "Audio",
    "description": "Rugged IPX7 waterproof speaker delivering 14W stereo sound, deep bass radiators, and 12-hour continuous battery.",
    "price": 1799,
    "originalPrice": 2999,
    "discount": 40,
    "rating": 4.5,
    "reviews": 310,
    "reviewCount": 310,
    "stock": 25,
    "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
    "tags": [
      "speaker",
      "bluetooth",
      "audio",
      "waterproof",
      "electronics"
    ],
    "variants": null
  },
  {
    "id": 21,
    "name": "Stainless Steel Espresso Machine",
    "brand": "De'Longhi",
    "category": "home",
    "subcategory": "Kitchen Appliances",
    "description": "15-bar professional pressure pump, manual milk frother steam wand, and compact brushed stainless steel chassis.",
    "price": 7499,
    "originalPrice": 11999,
    "discount": 38,
    "rating": 4.7,
    "reviews": 180,
    "reviewCount": 180,
    "stock": 9,
    "image": "https://images.unsplash.com/photo-1608354580875-30bd4168b351?w=600&q=80",
    "tags": [
      "espresso",
      "coffee machine",
      "kitchen appliances",
      "home",
      "coffee"
    ],
    "variants": null
  },
  {
    "id": 22,
    "name": "Non-Stick Ceramic Cookware 5-Piece Set",
    "brand": "Prestige",
    "category": "home",
    "subcategory": "Cookware",
    "description": "PTFE/PFOA-free non-toxic ceramic coating with stay-cool silicone handles and induction-compatible bases.",
    "price": 3299,
    "originalPrice": 5499,
    "discount": 40,
    "rating": 4.6,
    "reviews": 220,
    "reviewCount": 220,
    "stock": 14,
    "image": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80",
    "tags": [
      "cookware",
      "pots and pans",
      "non-stick",
      "kitchen",
      "home"
    ],
    "variants": null
  },
  {
    "id": 23,
    "name": "High-Speed Countertop Blender",
    "brand": "Philips",
    "category": "home",
    "subcategory": "Kitchen Appliances",
    "description": "1200W motor with 6-leaf stainless steel crushing blades, 2L BPA-free tritan jar, and variable speed dials.",
    "price": 2699,
    "originalPrice": 4299,
    "discount": 37,
    "rating": 4.5,
    "reviews": 195,
    "reviewCount": 195,
    "stock": 18,
    "image": "https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/thumbnail.webp",
    "tags": [
      "blender",
      "mixer",
      "kitchen appliances",
      "smoothies",
      "home"
    ],
    "variants": null
  },
  {
    "id": 24,
    "name": "16-Piece Porcelain Dinnerware Set",
    "brand": "Corelle",
    "category": "home",
    "subcategory": "Dining",
    "description": "Chip-resistant microwave and dishwasher safe porcelain set featuring 4 dinner plates, 4 salad plates, and bowls.",
    "price": 2199,
    "originalPrice": 3499,
    "discount": 37,
    "rating": 4.6,
    "reviews": 165,
    "reviewCount": 165,
    "stock": 15,
    "image": "https://cdn.dummyjson.com/product-images/kitchen-accessories/plate/thumbnail.webp",
    "tags": [
      "dinnerware",
      "plates",
      "porcelain",
      "dining",
      "home"
    ],
    "variants": null
  },
  {
    "id": 25,
    "name": "100% Organic Cotton Bed Sheet Set",
    "brand": "Spaces",
    "category": "home",
    "subcategory": "Bedding",
    "description": "400 thread-count sateen weave organic cotton fitted sheet, flat sheet, and matching pillowcases.",
    "price": 1599,
    "originalPrice": 2799,
    "discount": 43,
    "rating": 4.6,
    "reviews": 240,
    "reviewCount": 240,
    "stock": 22,
    "image": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
    "tags": [
      "bedsheet",
      "bedding",
      "cotton",
      "linen",
      "bedroom",
      "home"
    ],
    "variants": [
      "Single",
      "Queen",
      "King"
    ]
  },
  {
    "id": 26,
    "name": "Ergonomic Memory Foam Pillow",
    "brand": "Wakefit",
    "category": "home",
    "subcategory": "Bedding",
    "description": "Contoured cervical orthopedic memory foam pillow with breathable bamboo fiber removable cover.",
    "price": 899,
    "originalPrice": 1599,
    "discount": 44,
    "rating": 4.5,
    "reviews": 310,
    "reviewCount": 310,
    "stock": 28,
    "image": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&q=80",
    "tags": [
      "pillow",
      "memory foam",
      "bedding",
      "orthopedic",
      "home"
    ],
    "variants": null
  },
  {
    "id": 27,
    "name": "Stainless Steel Electric Kettle 1.8L",
    "brand": "Pigeon",
    "category": "home",
    "subcategory": "Kitchen Appliances",
    "description": "Fast-boiling 1500W cordless electric kettle with auto shut-off, boil-dry protection, and 360-degree swivel base.",
    "price": 749,
    "originalPrice": 1299,
    "discount": 42,
    "rating": 4.4,
    "reviews": 420,
    "reviewCount": 420,
    "stock": 35,
    "image": "https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp",
    "tags": [
      "kettle",
      "electric kettle",
      "kitchen appliances",
      "home"
    ],
    "variants": null
  },
  {
    "id": 28,
    "name": "Aroma Diffuser & Essential Oil Humidifier",
    "brand": "PureMist",
    "category": "home",
    "subcategory": "Home Decor",
    "description": "Ultrasonic cool mist humidifier with 7 soothing ambient LED light modes and whisper-quiet operation.",
    "price": 999,
    "originalPrice": 1799,
    "discount": 44,
    "rating": 4.5,
    "reviews": 188,
    "reviewCount": 188,
    "stock": 24,
    "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80",
    "tags": [
      "diffuser",
      "humidifier",
      "aromatherapy",
      "home decor",
      "home"
    ],
    "variants": null
  },
  {
    "id": 29,
    "name": "Modern Ceramic Flower Vase",
    "brand": "Home Centre",
    "category": "home",
    "subcategory": "Home Decor",
    "description": "Handcrafted matte textured ceramic vase with minimalist geometric silhouette suited for dried or fresh florals.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "rating": 4.4,
    "reviews": 125,
    "reviewCount": 125,
    "stock": 30,
    "image": "https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=600&q=80",
    "tags": [
      "vase",
      "ceramic",
      "home decor",
      "flowers",
      "home"
    ],
    "variants": null
  },
  {
    "id": 30,
    "name": "Chef Damascus Steel Kitchen Knife (8-inch)",
    "brand": "Wüsthof",
    "category": "home",
    "subcategory": "Cutlery",
    "description": "High-carbon 67-layer Damascus steel blade with razor-sharp 15-degree edge and ergonomic Pakkawood handle.",
    "price": 1499,
    "originalPrice": 2499,
    "discount": 40,
    "rating": 4.7,
    "reviews": 145,
    "reviewCount": 145,
    "stock": 17,
    "image": "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&q=80",
    "tags": [
      "knife",
      "chef knife",
      "cutlery",
      "kitchen",
      "cookware",
      "home"
    ],
    "variants": null
  },
  {
    "id": 31,
    "name": "Adjustable Dumbbell Set (5-50 lbs)",
    "brand": "Bowflex",
    "category": "sports",
    "subcategory": "Fitness Equipment",
    "description": "Rapid weight adjustment dial replacing 15 sets of weights in a compact space-saving home workout station.",
    "price": 4999,
    "originalPrice": 8999,
    "discount": 44,
    "rating": 4.8,
    "reviews": 310,
    "reviewCount": 310,
    "stock": 11,
    "image": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80",
    "tags": [
      "dumbbells",
      "weights",
      "fitness",
      "gym",
      "workout",
      "sports"
    ],
    "variants": null
  },
  {
    "id": 32,
    "name": "Non-Slip Extra-Thick Yoga Mat (6mm)",
    "brand": "Lululemon",
    "category": "sports",
    "subcategory": "Yoga & Pilates",
    "description": "Eco-friendly TPE high-density cushioned mat with laser-engraved alignment lines and anti-tear mesh.",
    "price": 999,
    "originalPrice": 1799,
    "discount": 44,
    "rating": 4.7,
    "reviews": 415,
    "reviewCount": 415,
    "stock": 28,
    "image": "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&q=80",
    "tags": [
      "yoga mat",
      "exercise",
      "pilates",
      "fitness",
      "sports"
    ],
    "variants": null
  },
  {
    "id": 33,
    "name": "English Willow Cricket Bat",
    "brand": "SS Ton",
    "category": "sports",
    "subcategory": "Cricket",
    "description": "Grade 1 English willow hand-crafted with thick contoured edges, concave profile, and multi-piece cane handle.",
    "price": 3999,
    "originalPrice": 6499,
    "discount": 38,
    "rating": 4.7,
    "reviews": 260,
    "reviewCount": 260,
    "stock": 15,
    "image": "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-bat/thumbnail.webp",
    "tags": [
      "cricket",
      "bat",
      "cricket bat",
      "sports",
      "willow"
    ],
    "variants": null
  },
  {
    "id": 34,
    "name": "Official Size 5 Match Football",
    "brand": "Mitre",
    "category": "sports",
    "subcategory": "Football",
    "description": "Thermally bonded seamless surface with reinforced butyl bladder for optimal air retention and true flight trajectory.",
    "price": 899,
    "originalPrice": 1599,
    "discount": 44,
    "rating": 4.6,
    "reviews": 340,
    "reviewCount": 340,
    "stock": 30,
    "image": "https://cdn.dummyjson.com/product-images/sports-accessories/football/thumbnail.webp",
    "tags": [
      "football",
      "soccer",
      "ball",
      "sports",
      "match ball"
    ],
    "variants": null
  },
  {
    "id": 35,
    "name": "Professional Badminton Racket Set",
    "brand": "Yonex",
    "category": "sports",
    "subcategory": "Racket Sports",
    "description": "Full carbon graphite frame engineered with isometric head shape, includes 2 rackets and nylon shuttlecocks.",
    "price": 1699,
    "originalPrice": 2799,
    "discount": 39,
    "rating": 4.6,
    "reviews": 280,
    "reviewCount": 280,
    "stock": 20,
    "image": "https://cdn.dummyjson.com/product-images/sports-accessories/tennis-racket/thumbnail.webp",
    "tags": [
      "badminton",
      "racket",
      "shuttlecock",
      "sports",
      "tennis"
    ],
    "variants": null
  },
  {
    "id": 36,
    "name": "32 oz Insulated Stainless Sports Bottle",
    "brand": "Hydro Flask",
    "category": "sports",
    "subcategory": "Hydration",
    "description": "Double-wall vacuum insulation keeping drinks icy cold for 24 hours or steaming hot for 12 hours with leakproof straw lid.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "rating": 4.7,
    "reviews": 390,
    "reviewCount": 390,
    "stock": 45,
    "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    "tags": [
      "water bottle",
      "flask",
      "hydration",
      "sports",
      "gym"
    ],
    "variants": null
  },
  {
    "id": 37,
    "name": "Resistance Exercise Bands Set (5 Levels)",
    "brand": "CultSport",
    "category": "sports",
    "subcategory": "Fitness Equipment",
    "description": "100% natural latex loop bands ranging from X-Light to X-Heavy with carry pouch and workout manual.",
    "price": 449,
    "originalPrice": 899,
    "discount": 50,
    "rating": 4.5,
    "reviews": 270,
    "reviewCount": 270,
    "stock": 50,
    "image": "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600&q=80",
    "tags": [
      "resistance bands",
      "fitness",
      "workout",
      "gym",
      "sports"
    ],
    "variants": null
  },
  {
    "id": 38,
    "name": "Speed Skipping Jump Rope with Bearings",
    "brand": "Everlast",
    "category": "sports",
    "subcategory": "Fitness Equipment",
    "description": "360-degree ball bearing rotation with tangle-free steel wire cable and non-slip aluminum alloy handles.",
    "price": 349,
    "originalPrice": 699,
    "discount": 50,
    "rating": 4.4,
    "reviews": 210,
    "reviewCount": 210,
    "stock": 40,
    "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    "tags": [
      "jump rope",
      "skipping rope",
      "cardio",
      "fitness",
      "sports"
    ],
    "variants": null
  },
  {
    "id": 39,
    "name": "Waterproof Hiking Backpack 40L",
    "brand": "Wildcraft",
    "category": "sports",
    "subcategory": "Outdoor & Hiking",
    "description": "Ripstop nylon waterproof backpack with ergonomic ventilated back panel, rain cover, and trekking pole attachments.",
    "price": 1899,
    "originalPrice": 3299,
    "discount": 42,
    "rating": 4.6,
    "reviews": 195,
    "reviewCount": 195,
    "stock": 16,
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    "tags": [
      "backpack",
      "hiking",
      "trekking",
      "camping",
      "sports",
      "travel"
    ],
    "variants": null
  },
  {
    "id": 40,
    "name": "Cycling & Skateboard Safety Helmet",
    "brand": "Decathlon",
    "category": "sports",
    "subcategory": "Cycling",
    "description": "CPSC certified shock-absorbing EPS foam core with durable ABS outer shell, dial-fit system, and 12 cooling vents.",
    "price": 1199,
    "originalPrice": 1999,
    "discount": 40,
    "rating": 4.5,
    "reviews": 155,
    "reviewCount": 155,
    "stock": 22,
    "image": "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=600&q=80",
    "tags": [
      "helmet",
      "cycling",
      "safety",
      "sports",
      "skating"
    ],
    "variants": [
      "M",
      "L"
    ]
  },
  {
    "id": 41,
    "name": "Atomic Habits by James Clear",
    "brand": "Penguin Random House",
    "category": "books",
    "subcategory": "Self-Help",
    "description": "An easy and proven way to build good habits and break bad ones using neuroscience and practical frameworks.",
    "price": 499,
    "originalPrice": 799,
    "discount": 38,
    "rating": 4.9,
    "reviews": 980,
    "reviewCount": 980,
    "stock": 35,
    "image": "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    "tags": [
      "books",
      "habits",
      "self-help",
      "productivity",
      "non-fiction"
    ],
    "variants": null
  },
  {
    "id": 42,
    "name": "The Silent Patient by Alex Michaelides",
    "brand": "Celadon Books",
    "category": "books",
    "subcategory": "Psychological Thriller",
    "description": "A shocking psychological thriller of a woman's act of violence against her husband and the therapist obsessed with uncovering her motive.",
    "price": 399,
    "originalPrice": 650,
    "discount": 39,
    "rating": 4.7,
    "reviews": 720,
    "reviewCount": 720,
    "stock": 28,
    "image": "https://covers.openlibrary.org/b/id/9407338-L.jpg",
    "tags": [
      "books",
      "thriller",
      "mystery",
      "fiction",
      "novel"
    ],
    "variants": null
  },
  {
    "id": 43,
    "name": "The Joy of Cooking by Irma S. Rombauer",
    "brand": "Scribner",
    "category": "books",
    "subcategory": "Cookbooks",
    "description": "The quintessential all-purpose American cookbook packed with over 4,000 tested kitchen-tested recipes and culinary fundamentals.",
    "price": 899,
    "originalPrice": 1499,
    "discount": 40,
    "rating": 4.8,
    "reviews": 340,
    "reviewCount": 340,
    "stock": 15,
    "image": "https://covers.openlibrary.org/b/id/475157-L.jpg",
    "tags": [
      "books",
      "cookbook",
      "recipes",
      "cooking",
      "food"
    ],
    "variants": null
  },
  {
    "id": 44,
    "name": "Zero to One by Peter Thiel",
    "brand": "Crown Business",
    "category": "books",
    "subcategory": "Business & Startups",
    "description": "Notes on startups, building technology companies, and how to create breakthrough value in the modern economy.",
    "price": 449,
    "originalPrice": 699,
    "discount": 36,
    "rating": 4.7,
    "reviews": 650,
    "reviewCount": 650,
    "stock": 30,
    "image": "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
    "tags": [
      "books",
      "business",
      "startups",
      "technology",
      "entrepreneurship"
    ],
    "variants": null
  },
  {
    "id": 45,
    "name": "Bedtime Stories for Kids",
    "brand": "Disney Press",
    "category": "books",
    "subcategory": "Children Books",
    "description": "A heartwarming collection of beautifully illustrated classic tales designed to calm and delight young children at bedtime.",
    "price": 349,
    "originalPrice": 599,
    "discount": 42,
    "rating": 4.6,
    "reviews": 290,
    "reviewCount": 290,
    "stock": 40,
    "image": "https://covers.openlibrary.org/b/id/35556-L.jpg",
    "tags": [
      "books",
      "children",
      "stories",
      "kids",
      "illustrated"
    ],
    "variants": null
  },
  {
    "id": 46,
    "name": "A Brief History of Time by Stephen Hawking",
    "brand": "Bantam Books",
    "category": "books",
    "subcategory": "Popular Science",
    "description": "Stephen Hawking's worldwide masterpiece exploring black holes, gravitational singularities, the Big Bang, and cosmology.",
    "price": 429,
    "originalPrice": 699,
    "discount": 39,
    "rating": 4.8,
    "reviews": 810,
    "reviewCount": 810,
    "stock": 25,
    "image": "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
    "tags": [
      "books",
      "science",
      "physics",
      "cosmology",
      "non-fiction"
    ],
    "variants": null
  },
  {
    "id": 47,
    "name": "Thinking, Fast and Slow by Daniel Kahneman",
    "brand": "Farrar, Straus and Giroux",
    "category": "books",
    "subcategory": "Psychology",
    "description": "Nobel laureate Daniel Kahneman reveals the two systems that drive the way we think: intuitive fast thinking versus deliberate slow thinking.",
    "price": 529,
    "originalPrice": 899,
    "discount": 41,
    "rating": 4.8,
    "reviews": 610,
    "reviewCount": 610,
    "stock": 22,
    "image": "https://covers.openlibrary.org/b/isbn/9780374275631-L.jpg",
    "tags": [
      "books",
      "psychology",
      "behavioral economics",
      "decision making"
    ],
    "variants": null
  },
  {
    "id": 48,
    "name": "The Psychology of Money by Morgan Housel",
    "brand": "Harriman House",
    "category": "books",
    "subcategory": "Personal Finance",
    "description": "Timeless lessons on wealth, greed, and happiness exploring how people think about money and financial independence.",
    "price": 379,
    "originalPrice": 599,
    "discount": 37,
    "rating": 4.9,
    "reviews": 940,
    "reviewCount": 940,
    "stock": 35,
    "image": "https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg",
    "tags": [
      "books",
      "money",
      "finance",
      "investing",
      "wealth"
    ],
    "variants": null
  },
  {
    "id": 49,
    "name": "Deep Work by Cal Newport",
    "brand": "Grand Central Publishing",
    "category": "books",
    "subcategory": "Productivity",
    "description": "Rules for focused success in a distracted world, teaching how to master complicated information and produce better results in less time.",
    "price": 419,
    "originalPrice": 699,
    "discount": 40,
    "rating": 4.7,
    "reviews": 540,
    "reviewCount": 540,
    "stock": 26,
    "image": "https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg",
    "tags": [
      "books",
      "productivity",
      "focus",
      "deep work",
      "career"
    ],
    "variants": null
  },
  {
    "id": 50,
    "name": "To Kill a Mockingbird by Harper Lee",
    "brand": "HarperCollins",
    "category": "books",
    "subcategory": "Classic Literature",
    "description": "The Pulitzer Prize-winning classic novel of warmth and humor tackling the roots of human behavior, prejudice, and moral courage.",
    "price": 329,
    "originalPrice": 499,
    "discount": 34,
    "rating": 4.9,
    "reviews": 1100,
    "reviewCount": 1100,
    "stock": 30,
    "image": "https://covers.openlibrary.org/b/isbn/9780060935467-L.jpg",
    "tags": [
      "books",
      "literature",
      "classics",
      "fiction",
      "novel"
    ],
    "variants": null
  },
  {
    "id": 51,
    "name": "Hydrating Hyaluronic Acid Facial Serum",
    "brand": "The Ordinary",
    "category": "beauty",
    "subcategory": "Skincare",
    "description": "Multi-depth hydration formulation with ultra-pure vegan hyaluronic acid and soothing vitamin B5.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "rating": 4.7,
    "reviews": 480,
    "reviewCount": 480,
    "stock": 32,
    "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80",
    "tags": [
      "serum",
      "skincare",
      "hyaluronic acid",
      "hydrating",
      "beauty"
    ],
    "variants": null
  },
  {
    "id": 52,
    "name": "Broad-Spectrum SPF 50 Mineral Sunscreen",
    "brand": "Neutrogena",
    "category": "beauty",
    "subcategory": "Suncare",
    "description": "Sheer ultra-lightweight water-resistant zinc oxide sunscreen offering UVA/UVB defense without greasy residue or white cast.",
    "price": 549,
    "originalPrice": 899,
    "discount": 39,
    "rating": 4.6,
    "reviews": 390,
    "reviewCount": 390,
    "stock": 38,
    "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    "tags": [
      "sunscreen",
      "spf",
      "suncare",
      "skincare",
      "beauty"
    ],
    "variants": null
  },
  {
    "id": 53,
    "name": "Nourishing Moroccan Argan Oil Shampoo",
    "brand": "OGX",
    "category": "beauty",
    "subcategory": "Haircare",
    "description": "Sulfate-free restoring shampoo infused with precious Moroccan argan oil to revive softness, shine, and silky strength.",
    "price": 649,
    "originalPrice": 999,
    "discount": 35,
    "rating": 4.5,
    "reviews": 310,
    "reviewCount": 310,
    "stock": 26,
    "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&q=80",
    "tags": [
      "shampoo",
      "argan oil",
      "haircare",
      "beauty",
      "sulfate-free"
    ],
    "variants": null
  },
  {
    "id": 54,
    "name": "Ionic Salon-Grade Blow Hair Dryer",
    "brand": "Dyson",
    "category": "beauty",
    "subcategory": "Hair Tools",
    "description": "High-velocity 1800W brushless motor with negative ion generator, diffuser nozzle, and 3 heat settings for frizz-free drying.",
    "price": 2799,
    "originalPrice": 4499,
    "discount": 38,
    "rating": 4.8,
    "reviews": 220,
    "reviewCount": 220,
    "stock": 14,
    "image": "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=600&q=80",
    "tags": [
      "hair dryer",
      "hair styling",
      "tools",
      "beauty",
      "salon"
    ],
    "variants": null
  },
  {
    "id": 55,
    "name": "Long-Lasting Glossy Gel Nail Polish",
    "brand": "O.P.I",
    "category": "beauty",
    "subcategory": "Nails",
    "description": "Chip-resistant, salon-quality high-shine lacquer providing up to 14 days of chip-free vibrant wear with wide pro-brush.",
    "price": 349,
    "originalPrice": 599,
    "discount": 42,
    "rating": 4.4,
    "reviews": 165,
    "reviewCount": 165,
    "stock": 40,
    "image": "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp",
    "tags": [
      "nail polish",
      "nails",
      "manicure",
      "beauty",
      "cosmetics"
    ],
    "variants": null
  },
  {
    "id": 56,
    "name": "Purifying Herbal Green Tea Clay Face Mask",
    "brand": "Innisfree",
    "category": "beauty",
    "subcategory": "Skincare",
    "description": "Mineral-rich kaolin volcanic clay mask enriched with Jeju green tea extract to absorb excess sebum and unclog pores.",
    "price": 499,
    "originalPrice": 799,
    "discount": 38,
    "rating": 4.6,
    "reviews": 275,
    "reviewCount": 275,
    "stock": 30,
    "image": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80",
    "tags": [
      "face mask",
      "clay mask",
      "skincare",
      "pore cleansing",
      "beauty"
    ],
    "variants": null
  },
  {
    "id": 57,
    "name": "Matte Velvet Longwear Liquid Lipstick",
    "brand": "MAC",
    "category": "beauty",
    "subcategory": "Makeup",
    "description": "Weightless transfer-proof liquid lipstick delivering intense bold pigmentation with a comfortable 16-hour velvety finish.",
    "price": 899,
    "originalPrice": 1499,
    "discount": 40,
    "rating": 4.7,
    "reviews": 360,
    "reviewCount": 360,
    "stock": 25,
    "image": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&q=80",
    "tags": [
      "lipstick",
      "liquid lipstick",
      "matte",
      "makeup",
      "beauty",
      "cosmetics"
    ],
    "variants": null
  },
  {
    "id": 58,
    "name": "Gentle Foaming Hydrating Facial Cleanser",
    "brand": "CeraVe",
    "category": "beauty",
    "subcategory": "Skincare",
    "description": "Non-comedogenic daily foaming face wash formulated with 3 essential ceramides, hyaluronic acid, and niacinamide.",
    "price": 599,
    "originalPrice": 999,
    "discount": 40,
    "rating": 4.8,
    "reviews": 510,
    "reviewCount": 510,
    "stock": 34,
    "image": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80",
    "tags": [
      "cleanser",
      "face wash",
      "ceramides",
      "skincare",
      "beauty"
    ],
    "variants": null
  },
  {
    "id": 59,
    "name": "Volumizing & Lengthening Waterproof Mascara",
    "brand": "Maybelline",
    "category": "beauty",
    "subcategory": "Eye Makeup",
    "description": "Buildable clump-resistant mascara with flexible silicone wand for dramatic fanned-out lash volume that lasts all day.",
    "price": 399,
    "originalPrice": 649,
    "discount": 39,
    "rating": 4.6,
    "reviews": 420,
    "reviewCount": 420,
    "stock": 36,
    "image": "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=600&q=80",
    "tags": [
      "mascara",
      "lashes",
      "eye makeup",
      "waterproof",
      "beauty"
    ],
    "variants": null
  },
  {
    "id": 60,
    "name": "Rose Water Soothing Facial Toner Mist",
    "brand": "Forest Essentials",
    "category": "beauty",
    "subcategory": "Skincare",
    "description": "Steam-distilled pure rose water face mist providing instant refreshing hydration, balanced pH, and pore refinement.",
    "price": 499,
    "originalPrice": 799,
    "discount": 38,
    "rating": 4.6,
    "reviews": 230,
    "reviewCount": 230,
    "stock": 28,
    "image": "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=600&q=80",
    "tags": [
      "toner",
      "rose water",
      "face mist",
      "skincare",
      "beauty",
      "natural"
    ],
    "variants": null
  }
];

const seedProducts = async () => {
  try {
    await connectDB();
    if (!isConnected()) {
      console.log('[Seed] Notice: MongoDB not connected. Seed script ready for when DB is active.');
      return defaultProducts;
    }

    console.log('[Seed] Clearing existing products...');
    await Product.deleteMany({});

    console.log('[Seed] Inserting ' + defaultProducts.length + ' verified products...');
    const result = await Product.insertMany(defaultProducts);
    console.log('[Seed] Successfully seeded ' + result.length + ' products!');
    return result;
  } catch (err) {
    console.error('[Seed] Error during seeding:', err.message);
  } finally {
    if (mongoose.connection.readyState !== 0) {
      await mongoose.connection.close();
    }
  }
};

if (require.main === module) {
  seedProducts().then(() => process.exit(0));
}

module.exports = { defaultProducts, seedProducts };
